### PR TITLE
Add ESP32 for Software Serial

### PR DESCRIPTION
**Pull request by Mr-HaleYa**

### CODE REVIEW

**Comment by ladyada** [comment]
hi it does not compile, please fix so it compiles and let us know when its working!

**Comment by Mr-HaleYa** [comment]
image
compiles just fine for me and it's the only way to get the camera to work for me. What is your configuration?

**Comment by Mr-HaleYa** [comment]
actually, nevermind I'm just going to customize this to work for me

**Comment by ladyada** [comment]
oki! if you want to readd it, the library has to be added as a dependency in library.properties!

**Pull request closed without merging**
